apiVersion: apps/v1
kind: Deployment
metadata:
  name: mt5-boris
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mt5-trading
  template:
    metadata:
      labels:
        app: mt5-trading
    spec:
      # 1. DNS Çözümü: Google DNS'lerini konteynere zorla tanıtıyoruz
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4
      containers:
      - name: mt5-container
        image: docker.io/boris2015/mt5:latest
        # 2. İzin Çözümü: Konteynere daha fazla yetki veriyoruz (Wine için kritik)
        securityContext:
          privileged: true 
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
        volumeMounts:
        - name: mt5-storage
          # Loglara göre boris imajı /config klasörünü kullanıyor
          mountPath: /config 
      volumes:
      - name: mt5-storage
        hostPath:
          path: /mnt/mt5-data
          type: DirectoryOrCreate